### ISSUE TITLE
train.py not accepting sample rates other than 16000 | ValueError: could not broadcast input array from shape (1,32000) into shape (1,16000)

### ISSUE THREAD

**Issue by Ma5onic** [seth814/Audio-Classification#25]
After fixing/bypassing issue #14, `python train.py` seems to dislike sample rates other than 16000:
```
Traceback (most recent call last):
  File "train.py", line 114, in <module>
    train(args)
  File "train.py", line 96, in train
    callbacks=[csv_logger, cp])
  File "/home/myuser/anaconda3/envs/audio/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/training.py", line 819, in fit
    use_multiprocessing=use_multiprocessing)
  File "/home/myuser/anaconda3/envs/audio/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/training_v2.py", line 235, in fit
    use_multiprocessing=use_multiprocessing)
  File "/home/myuser/anaconda3/envs/audio/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/training_v2.py", line 593, in _process_training_inputs
    use_multiprocessing=use_multiprocessing)
  File "/home/myuser/anaconda3/envs/audio/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/training_v2.py", line 706, in _process_inputs
    use_multiprocessing=use_multiprocessing)
  File "/home/myuser/anaconda3/envs/audio/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/data_adapter.py", line 952, in __init__
    **kwargs)
  File "/home/myuser/anaconda3/envs/audio/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/data_adapter.py", line 747, in __init__
    peek, x = self._peek_and_restore(x)
  File "/home/myuser/anaconda3/envs/audio/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/data_adapter.py", line 956, in _peek_and_restore
    return x[0], x
  File "train.py", line 46, in __getitem__
    X[i,] = wav.reshape(1, -1)
ValueError: could not broadcast input array from shape (1,32000) into shape (1,16000)
```

**Comment by Ma5onic** [comment]
Issue solved by using the latest master branch.

**Comment by Ma5onic** [comment]
`python train.py` complains after the 1st epoch:
```
2020-07-08 06:54:04.006436: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libnvinfer.so.6
2020-07-08 06:54:04.007359: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libnvinfer_plugin.so.6
2020-07-08 06:54:05.018369: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcuda.so.1
2020-07-08 06:54:05.022380: E tensorflow/stream_executor/cuda/cuda_driver.cc:351] failed call to cuInit: CUDA_ERROR_COMPAT_NOT_SUPPORTED_ON_DEVICE: forward compatibility was attempted on non supported HW
2020-07-08 06:54:05.022401: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:169] retrieving CUDA diagnostic information for host: myuser
2020-07-08 06:54:05.022407: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:176] hostname: myuser
2020-07-08 06:54:05.022506: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:200] libcuda reported version is: 450.51.5
2020-07-08 06:54:05.022525: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:204] kernel reported version is: 440.100.0
2020-07-08 06:54:05.022531: E tensorflow/stream_executor/cuda/cuda_diagnostics.cc:313] kernel version 440.100.0 does not match DSO version 450.51.5 -- cannot find working devices in this configuration
2020-07-08 06:54:05.022746: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2020-07-08 06:54:05.027262: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 4120225000 Hz
2020-07-08 06:54:05.027662: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x56528f60c990 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-07-08 06:54:05.027675: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
/home/myuser/anaconda3/envs/audio/lib/python3.7/site-packages/librosa/filters.py:196: FutureWarning: norm=1 behavior will change in librosa 0.8.0. To maintain forward compatibility, use norm='slaney' instead.
  FutureWarning)
WARNING:tensorflow:sample_weight modes were coerced from
  ...
    to  
  ['...']
WARNING:tensorflow:sample_weight modes were coerced from
  ...
    to  
  ['...']
Train for 94 steps, validate for 10 steps
Epoch 1/30
93/94 [============================>.] - ETA: 0s - loss: 2.7065 - accuracy: 0.20032020-07-08 06:54:14.433587: W tensorflow/core/common_runtime/base_collective_executor.cc:217] BaseCollectiveExecutor::StartAbort Invalid argument: logits and labels must be broadcastable: logits_size=[16,21] labels_size=[16,20]
	 [[{{node loss/softmax_loss/softmax_cross_entropy_with_logits}}]]
WARNING:tensorflow:Can save best model only with val_loss available, skipping.
94/94 [==============================] - 8s 85ms/step - loss: 2.7012 - accuracy: 0.2015
Traceback (most recent call last):
  File "train.py", line 118, in <module>
    train(args)
  File "train.py", line 100, in train
    callbacks=[csv_logger, cp])
  File "/home/myuser/anaconda3/envs/audio/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/training.py", line 819, in fit
    use_multiprocessing=use_multiprocessing)
  File "/home/myuser/anaconda3/envs/audio/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/training_v2.py", line 395, in fit
    total_epochs=1)
  File "/home/myuser/anaconda3/envs/audio/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/training_v2.py", line 128, in run_one_epoch
    batch_outs = execution_function(iterator)
  File "/home/myuser/anaconda3/envs/audio/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/training_v2_utils.py", line 98, in execution_function
    distributed_function(input_fn))
  File "/home/myuser/anaconda3/envs/audio/lib/python3.7/site-packages/tensorflow_core/python/eager/def_function.py", line 568, in __call__
    result = self._call(*args, **kwds)
  File "/home/myuser/anaconda3/envs/audio/lib/python3.7/site-packages/tensorflow_core/python/eager/def_function.py", line 638, in _call
    return self._concrete_stateful_fn._filtered_call(canon_args, canon_kwds)  # pylint: disable=protected-access
  File "/home/myuser/anaconda3/envs/audio/lib/python3.7/site-packages/tensorflow_core/python/eager/function.py", line 1611, in _filtered_call
    self.captured_inputs)
  File "/home/myuser/anaconda3/envs/audio/lib/python3.7/site-packages/tensorflow_core/python/eager/function.py", line 1692, in _call_flat
    ctx, args, cancellation_manager=cancellation_manager))
  File "/home/myuser/anaconda3/envs/audio/lib/python3.7/site-packages/tensorflow_core/python/eager/function.py", line 545, in call
    ctx=ctx)
  File "/home/myuser/anaconda3/envs/audio/lib/python3.7/site-packages/tensorflow_core/python/eager/execute.py", line 67, in quick_execute
    six.raise_from(core._status_to_exception(e.code, message), None)
  File "<string>", line 3, in raise_from
tensorflow.python.framework.errors_impl.InvalidArgumentError:  logits and labels must be broadcastable: logits_size=[16,21] labels_size=[16,20]
	 [[node loss/softmax_loss/softmax_cross_entropy_with_logits (defined at train.py:100) ]] [Op:__inference_distributed_function_9095]

Function call stack:
distributed_function
```
Do you have any suggestions?

**Comment by seth814** [comment]
check `len(args.src_root)` and `len(set(label_train))`

They should be the same.

I guess a class must be missing from label_train. Basically your model thinks there should be 21 classes but the labels are being produced as if there are 20.

**Comment by seth814** [comment]
Easy solution would be to change on lines 89 and 91

`len(set(label_train))` to `params['N_CLASSES']`

But this doesn't ensure all classes are present in the training data. I'll add a warning for it this weekend.
At least I think this is the issue you are having.

**Comment by seth814** [comment]
I made a warning to check for cases where not all classes are present in the train / val splits. Also the classes are set from the true n_classes present in src.root. This should fix your problem, but I'm not 100% sure.

**Comment by seth814** [comment]
Closing since this should be fixed now. If you're getting a warning, consider increasing data size, so all class labels are present in the training split.

**Comment by coolio51** [comment]
I am using the latest train.py but it still doesn't accept sample rates other than 16000.

`Traceback` (most recent call last):
  File "train.py", line 120, in <module>
    train(args)
  File "train.py", line 103, in train
    callbacks=[csv_logger, cp])
  File "C:\Users\solab\anaconda3\envs\AudioClass\lib\site-packages\tensorflow\python\keras\engine\training.py", line 108, in _method_wrapper
    return method(self, *args, **kwargs)
  File "C:\Users\solab\anaconda3\envs\AudioClass\lib\site-packages\tensorflow\python\keras\engine\training.py", line 1063, in fit
    steps_per_execution=self._steps_per_execution)
  File "C:\Users\solab\anaconda3\envs\AudioClass\lib\site-packages\tensorflow\python\keras\engine\data_adapter.py", line 1117, in __init__
    model=model)
  File "C:\Users\solab\anaconda3\envs\AudioClass\lib\site-packages\tensorflow\python\keras\engine\data_adapter.py", line 916, in __init__
    **kwargs)
  File "C:\Users\solab\anaconda3\envs\AudioClass\lib\site-packages\tensorflow\python\keras\engine\data_adapter.py", line 786, in __init__
    peek, x = self._peek_and_restore(x)
  File "C:\Users\solab\anaconda3\envs\AudioClass\lib\site-packages\tensorflow\python\keras\engine\data_adapter.py", line 920, in _peek_and_restore
    return x[0], x
  File "train.py", line 47, in __getitem__
    X[i,] = wav.reshape(-1, 1)
ValueError: could not broadcast input array from shape (352800,1) into shape (16000,1)``

Any suggestions?

**Comment by coolio51** [comment]
I am still having this issue with the new code:

This is my error code:
ValueError: could not broadcast input array from shape (352800,1) into shape (16000,1)

This is the error code from Ma5onic:
ValueError: could not broadcast input array from shape (1,32000) into shape (1,16000)

Do you have any idea why this happens?
